dist: xenial
sudo: true

arch:
  - amd64
  - ppc64le    

language: c++
      
script:
  - cd activemq-cpp
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - make doxygen-run
  - make check
  - cd src/test-integration
  - ./activemq-test-integration
