dist: xenial
sudo: true

arch:
  - amd64
  - ppc64le    

language: c++

addons:
  apt:
    packages:
      - uuid-dev
      - libcppunit-dev
      - APR
      - APR-Util
      
script:
  - cd activemq-cpp
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - make doxygen-run
  - make check
  - cd src/test-integration
  - ./activemq-test-integration
